### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-html-more-kinds-of-content-OSB7Pe#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-html-more-kinds-of-content-OSB7Pe/) and meets the following criteria:

- [x] Include [a haiku](http://www.kidzone.ws/poetry/haiku.htm), describing the feelings this product will evoke (with `br` elements to add new lines where appropriate)
- [x] [Create and download a sound effect file](http://sfbgames.com/chiptone/) for what the game will sound like when you win, then include an audio player in the page so users can hear the sample
- [x] Include a table comparing which features your game has in comparison to competitors (these competitors may be real or made up)
- [x] Include a demo video from YouTube, but featuring a completely unrelated animal being cute (not getting hurt!)

**Comment by chrisvfritz** [comment]
Nice favicon! 😝  And nice... everything else. Wow. I'm really impressed by your attention to detail.

- Code style
- Code organization
- Comments

It's all very professional. You even included some semantic elements (like `footer`) and `meta` elements (like `description`) that we haven't even released the lessons for yet! I give this 10/10 foxes:

🦊 🦊 🦊 🦊 🦊 🦊 🦊 🦊 🦊 🦊

And 1/1 squirrel:

💥  :shipit: 💥 

Are there any questions I can answer? More resources you'd like about something you worked on here, related to the project or not?
